variables:
  DEFECTDOJO_ENGAGEMENT_PERIOD: "7"
  DEFECTDOJO_ENGAGEMENT_STATUS: "Not Started"
  DEFECTDOJO_ENGAGEMENT_BUILD_SERVER: "null"
  DEFECTDOJO_ENGAGEMENT_SOURCE_CODE_MANAGEMENT_SERVER: "null"
  DEFECTDOJO_ENGAGEMENT_ORCHESTRATION_ENGINE: "null"
  DEFECTDOJO_ENGAGEMENT_DEDUPLICATION_ON_ENGAGEMENT: "false"
  DEFECTDOJO_ENGAGEMENT_THREAT_MODEL: "true"
  DEFECTDOJO_ENGAGEMENT_API_TEST: "true"
  DEFECTDOJO_ENGAGEMENT_PEN_TEST: "true"
  DEFECTDOJO_ENGAGEMENT_CHECK_LIST: "true"
  DEFECTDOJO_NOT_ON_MASTER: "false"
  DEFECTDOJO_ANCHORE_DISABLE: "false"
  DEFECTDOJO_URL: "http://host.docker.internal:8080/api/v2"
  DEFECTDOJO_TOKEN: "008ac80fe71c21784a5a4395092a00491900c1dc"
  AWS_ENDPOINT_URL: "http://host.docker.internal:9000/"
  AWS_ACCESS_KEY: "O8Z0hJ87F2IksIH3MOxy"
  AWS_SECRET_KEY: "xQJA5iHHchPk0KGnaWHWGn9bvYL6dKebiDdTRXfU"
  S3_BUCKET: "defectdojo"
  DEFECTDOJO_SCAN_MINIMUM_SEVERITY: "Info"
  DEFECTDOJO_SCAN_ACTIVE: "true"
  DEFECTDOJO_SCAN_VERIFIED: "true"
  DEFECTDOJO_SCAN_CLOSE_OLD_FINDINGS: "true"
  DEFECTDOJO_SCAN_ENVIRONMENT: "Default"
  DEFECTDOJO_SCAN_FILE_NAME: "gl-container-scanning-report.json"
  DEFECTDOJO_SCAN_DIRECTORY: "./scanresults/${DEFECTDOJO_SCAN_FILE_NAME}"
  DEFECTDOJO_IMAGE: "localhost:8090/defectdojo:latest"
  KANIKO_IMAGE: "localhost:8090/kaniko:latest"
  IMAGE_NAME: "defectdojo:latest"